# Generated by Django 3.1.2 on 2020-10-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='answer_ques',
            field=models.ManyToManyField(blank=True, to='qa.answers'),
        ),
    ]
